version: 0.2

phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...==========================================
      - export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID
      - export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY
      - aws ecr get-login-password --region ap-northeast-2 | docker login --username AWS --password-stdin 093272453328.dkr.ecr.ap-northeast-2.amazonaws.com
      - aws eks --region ap-northeast-2 update-kubeconfig --name newdeal
  install:
    runtime-versions:
      java: corretto11
  build:
    commands:
      - echo Started build phase..
      - mvn clean package
      - echo Building the Docker image...
      - docker build -t newdeal-backend .
      - docker tag newdeal-backend:latest 093272453328.dkr.ecr.ap-northeast-2.amazonaws.com/newdeal-backend:$CODEBUILD_RESOLVED_SOURCE_VERSION
  post_build:
    commands:
      - echo Build completed on `date`
      - echo Pushing the Docker image...
      - echo Image_Version - $CODEBUILD_RESOLVED_SOURCE_VERSION
      - docker push 093272453328.dkr.ecr.ap-northeast-2.amazonaws.com/newdeal-backend:$CODEBUILD_RESOLVED_SOURCE_VERSION
      - echo List directory
      - ls -la
      - echo Push the latest image to cluster
      - REPOSITORY_URI=093272453328.dkr.ecr.ap-northeast-2.amazonaws.com/newdeal-backend
      - sed -i 's@CONTAINER_IMAGE_TAG@'"$REPOSITORY_URI:$CODEBUILD_RESOLVED_SOURCE_VERSION"'@' k8s-deploy.yaml
      - DB_URL=${NEWDEAL_DATASOURCE_HOST}
      - sed -i 's@NEWDEAL_DATASOURCE_HOST_TAG@'"$DB_URL"'@' k8s-deploy.yaml
      - DB_PORT=${NEWDEAL_DATASOURCE_PORT}
      - sed -i 's@NEWDEAL_DATASOURCE_PORT_TAG@'"$DB_PORT"'@' k8s-deploy.yaml
      - DB_NAME=${NEWDEAL_DATASOURCE_DBNAME}
      - sed -i 's@NEWDEAL_DATASOURCE_DBNAME_TAG@'"$DB_NAME"'@' k8s-deploy.yaml
      - DB_USER=${NEWDEAL_DATASOURCE_USERNAME}
      - sed -i 's@NEWDEAL_DATASOURCE_USERNAME_TAG@'"$DB_USER"'@' k8s-deploy.yaml
      - DB_PWD=${NEWDEAL_DATASOURCE_PASSWORD}
      - sed -i 's@NEWDEAL_DATASOURCE_PASSWORD_TAG@'"$DB_PWD"'@' k8s-deploy.yaml
      - URL_FRONT=${NEWDEAL_API_FRONT_URL}
      - sed -i 's@NEWDEAL_API_FRONT_URL_TAG@'"$URL_FRONT"'@' k8s-deploy.yaml
      - URL_SECURITY=${NEWDEAL_API_SECURITY_URL}
      - sed -i 's@NEWDEAL_API_SECURITY_URL_TAG@'"$URL_SECURITY"'@' k8s-deploy.yaml
      - URL_BACKEND=${NEWDEAL_API_BACKEND_URL}
      - sed -i 's@NEWDEAL_API_BACKEND_URL_TAG@'"$URL_BACKEND"'@' k8s-deploy.yaml
      - URL_BACKEND_PROTOCOL=${NEWDEAL_API_BACKEND_PROTOCOL}
      - sed -i 's@NEWDEAL_API_BACKEND_PROTOCOL_TAG@'"$URL_BACKEND_PROTOCOL"'@' k8s-deploy.yaml
      - URL_FRONT_PROTOCOL=${NEWDEAL_API_FRONT_PROTOCOL}
      - sed -i 's@NEWDEAL_API_FRONT_PROTOCOL_TAG@'"$URL_FRONT_PROTOCOL"'@' k8s-deploy.yaml
      - URL_SECURITY_PROTOCOL=${NEWDEAL_API_SECURITY_PROTOCOL}
      - sed -i 's@NEWDEAL_API_SECURITY_PROTOCOL_TAG@'"$URL_SECURITY_PROTOCOL"'@' k8s-deploy.yaml
      - FILEUPLOAD_URL=${NEWDEAL_FILEUPLOAD_URL}
      - sed -i 's@NEWDEAL_FILEUPLOAD_URL_TAG@'"$FILEUPLOAD_URL"'@' k8s-deploy.yaml
      - NEWDEAL_AWS_PYTHON_API_URL=${NEWDEAL_AWS_PYTHON_API_URL}
      - sed -i 's@NEWDEAL_AWS_PYTHON_API_URL_TAG@'"$NEWDEAL_AWS_PYTHON_API_URL"'@' k8s-deploy.yaml
      - NEWDEAL_S3_ACCESS_ID=${NEWDEAL_S3_ACCESS_ID}
      - sed -i 's@NEWDEAL_S3_ACCESS_ID_TAG@'"$NEWDEAL_S3_ACCESS_ID"'@' k8s-deploy.yaml
      - NEWDEAL_S3_ACCESS_KEY=${NEWDEAL_S3_ACCESS_KEY}
      - sed -i 's@NEWDEAL_S3_ACCESS_KEY_TAG@'"$NEWDEAL_S3_ACCESS_KEY"'@' k8s-deploy.yaml
      - NEWDEAL_AWS_REGION=${NEWDEAL_AWS_REGION}
      - sed -i 's@NEWDEAL_AWS_REGION_TAG@'"$NEWDEAL_AWS_REGION"'@' k8s-deploy.yaml
      - NEWDEAL_AWS_S3_BUCKET=${NEWDEAL_AWS_S3_BUCKET}
      - sed -i 's@NEWDEAL_AWS_S3_BUCKET_TAG@'"$NEWDEAL_AWS_S3_BUCKET"'@' k8s-deploy.yaml
      - NEWDEAL_AWS_S3_BUCKET_URL=${NEWDEAL_AWS_S3_BUCKET_URL}
      - sed -i 's@NEWDEAL_AWS_S3_BUCKET_URL_TAG@'"$NEWDEAL_AWS_S3_BUCKET_URL"'@' k8s-deploy.yaml
      - NEWDEAL_AWS_POSTGRESQL_HOST=${NEWDEAL_AWS_POSTGRESQL_HOST}
      - sed -i 's@NEWDEAL_AWS_POSTGRESQL_HOST_TAG@'"$NEWDEAL_AWS_POSTGRESQL_HOST"'@' k8s-deploy.yaml
      - NEWDEAL_AWS_POSTGRESQL_PORT=${NEWDEAL_AWS_POSTGRESQL_PORT}
      - sed -i 's@NEWDEAL_AWS_POSTGRESQL_PORT_TAG@'"$NEWDEAL_AWS_POSTGRESQL_PORT"'@' k8s-deploy.yaml
      - NEWDEAL_AWS_POSTGRESQL_DBNAME=${NEWDEAL_AWS_POSTGRESQL_DBNAME}
      - sed -i 's@NEWDEAL_AWS_POSTGRESQL_DBNAME_TAG@'"$NEWDEAL_AWS_POSTGRESQL_DBNAME"'@' k8s-deploy.yaml
      - NEWDEAL_AWS_POSTGRESQL_USERNAME=${NEWDEAL_AWS_POSTGRESQL_USERNAME}
      - sed -i 's@NEWDEAL_AWS_POSTGRESQL_USERNAME_TAG@'"$NEWDEAL_AWS_POSTGRESQL_USERNAME"'@' k8s-deploy.yaml
      - NEWDEAL_AWS_POSTGRESQL_PASSWORD=${NEWDEAL_AWS_POSTGRESQL_PASSWORD}
      - sed -i 's@NEWDEAL_AWS_POSTGRESQL_PASSWORD_TAG@'"$NEWDEAL_AWS_POSTGRESQL_PASSWORD"'@' k8s-deploy.yaml
      - kubectl apply -f k8s-deploy.yaml
